title: 'zhihaofans'
subtitle: null
description: null
keywords: null
author: zhuang zhihao
language: zh-CN
timezone: Asia/Shanghai
url: 'https://zhihaofans.vercel.app'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
include:
  - "CNAME"
  - "image/*"
skip_render:
  - "CNAME"
new_post_name: ':year-:month-:day-:title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
# theme: next-git
theme: fluid
deploy:
  #type: git
  #repo: git@github.com:zhihaofans/zhihaofans.netlify.app.git # 使用仓库的ssh地址
  #branch: master
  #message: 更新时间：{{ now('YYYY-MM-DD HH:mm:ss') }}
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
search:
  path: search.xml
  field: post
  content: true
# 这里是next主题的配置
# theme_config:
#   minify: true
#   menu:
#     #categories: /categories/ || th
#     文章: /archives/ || archive
#     作品: /works.html || book
#     #schedule: /schedule/ || calendar
#     #sitemap: /sitemap.xml || sitemap
#     #commonweal: /404/ || heartbeat
#     #Android: /android/ || android
#     # 标签: /tags/ || tags
#     # 评测: /tags/评测/ ||shop
#     赞赏: https://afdian.net/@zhuangzhihao || money
#     关于: /about/me.html  || user
#   social:
#     GitHub: https://github.com/zhuangzhihao || github
#     Instagram: https://instagram.com/gho.zhuang || instagram
#     Twitter: https://twitter.com/zhuangzhihao_io || twitter
#   github_banner:
#     enable: false
#     permalink: https://github.com/zhuangzhihao
#     title: Follow me on GitHub
#   font:
#     enable: true
#     host: //fonts.loli.net
#   vendors:
#     fontawesome: //cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css
#     mathjax: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#     mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
#     katex: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
#     pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
#     jquery: //cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js
#     fancybox: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
#     fancybox_css: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
#     mediumzoom: //cdn.jsdelivr.net/npm/medium-zoom@1/dist/medium-zoom.min.js
#     lazyload: //cdn.jsdelivr.net/npm/lozad@1/dist/lozad.min.js
#     pangu: //cdn.jsdelivr.net/npm/pangu@4/dist/browser/pangu.min.js
#     quicklink: //cdn.jsdelivr.net/npm/quicklink@1/dist/quicklink.umd.js
#     disqusjs_js: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
#     disqusjs_css: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
#     valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
#     gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
#     gitalk_css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
#     algolia_instant_js: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.js
#     algolia_instant_css: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.css
#     pdfobject: //cdn.jsdelivr.net/npm/pdfobject@2/pdfobject.min.js
#     mermaid: //cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js
#     velocity: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.min.js
#     velocity_ui: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.ui.min.js
#     pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
#     pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/blue/pace-theme-minimal.css
#     three: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three.min.js
#     three_waves: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three-waves.min.js
#     canvas_lines: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_lines.min.js
#     canvas_sphere: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_sphere.min.js
#     canvas_nest: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
#     canvas_nest_nomobile: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js
#     canvas_ribbon: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js
#   footer:
#     since: 2019
  