lazyload:
  enable: true
  onlypost: false
about:
  icons:  # 不要把 icon 注释掉，否则无法覆盖配置
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/zhihaofans' }
navbar:
  blog_title: zhihaofans
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill', name: '文章' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'works', link: '/works.html', icon: 'iconfont icon-books', name: '作品'}
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }
force_https: true
index:
  slogan:
    enable: true
    text: 这是一个 Blog
  post_meta:
    date: true
    category: false
    tag: true
  auto_excerpt:
    enable: true
highlight:
  enable: true
  style: 'Github Gist'
  bg_color: false
  copy_btn: true
